---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Deployment template for a postgresql server with persistent storage.
    tags: "${NAME}-${TAG_NAME}"
  name: "${NAME}-deploy"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:    
    name: "${NAME}-${TAG_NAME}"
    generation: 1
    labels:
      app: "${NAME}-${TAG_NAME}"
      template: "${NAME}-deploy"
  spec:
    strategy:      
      type: Recreate
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - "${NAME}-${TAG_NAME}"
          from:
            kind: ImageStreamTag
            name: 'postgresql:10'
            namespace: openshift
      - type: ConfigChange  
    replicas: 1
    test: false
    selector:
      name: "${NAME}-${TAG_NAME}"
    template:
      metadata:
        labels:
          name: "${NAME}-${TAG_NAME}"
      spec:
        volumes:
        - name: "${NAME}-data"
          persistentVolumeClaim:
            claimName: "${NAME}-${TAG_NAME}"
        containers:
        - name: "${NAME}-${TAG_NAME}"
          image:  " "         
          ports:
            - containerPort: 5432
              protocol: TCP          
          env:
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: postgresql
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: postgresql
          - name: POSTGRESQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: postgresql          
          resources:
            limits:
              memory: 512Mi          
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: "${NAME}-data"   
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - '--live'          
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container            
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File                   
          imagePullPolicy: IfNotPresent          
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          securityContext:
            capabilities: {}
            privileged: false
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30        
        schedulerName: default-scheduler
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: "${NAME}-${TAG_NAME}"
    labels:
      app: "${NAME}-${TAG_NAME}"
      template: "${NAME}-deploy"
  spec:
    #storageClassName: "${PERSISTENT_VOLUME_CLASS}"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${PERSISTENT_VOLUME_SIZE}"        
  status:
    availableReplicas: 1
    conditions:
      - lastTransitionTime: '2023-03-11T03:31:54Z'
        lastUpdateTime: '2023-03-11T03:31:54Z'
        message: Deployment config has minimum availability.
        status: 'True'
        type: Available
      - lastTransitionTime: '2023-03-11T03:31:55Z'
        lastUpdateTime: '2023-03-11T03:31:55Z'
        message: replication controller "postgresql-1" successfully rolled out
        reason: NewReplicationControllerAvailable
        status: 'True'
        type: Progressing
    details:
      causes:
        - type: ConfigChange
      message: config change
    latestVersion: 1
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    unavailableReplicas: 0
    updatedReplicas: 1
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the OpenShift resources associated to the
    PostgreSQL instance.
  required: true
  value: postgresql-db
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
  value: dev
- name: PERSISTENT_VOLUME_SIZE
  displayName: Persistent Volume Size
  description: The size of the persistent volume , e.g. 512Mi, 1Gi, 2Gi.
  required: true
  value: 1Gi
- name: PERSISTENT_VOLUME_CLASS
  displayName: Persistent Volume Class name
  description: The class of the volume; gluster-file, gluster-block, gluster-file-db.
  required: false
  value: netapp-file-standard     
