---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Deployment template for a postgresql server with persistent storage.
    tags: "${NAME}-${TAG_NAME}"
  name: "${NAME}-deploy"
objects:
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    selector:
      app: ${NAME}
    replicas: 1
    template:
      metadata:
        labels:
          app: patroni
      spec:
        containers:
          - name: patroni
            image:  172.30.1.1:5000/myproject/patroni:v10-latest
            env:
              - name: PGHOST
                value: postgresql
              - name: PGPORT
                value: "5432"
              - name: PGUSER
                value: postgres
              - name: PGPASSWORD
                value: mypassword
            ports:
              - containerPort: 8008
            volumeMounts:
              - name: patroni-data
                mountPath: /home/postgres/pgdata
        volumes:
          - name: patroni-data
            persistentVolumeClaim:
              claimName: ${NAME}-${TAG_NAME}-data
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: "${NAME}-${TAG_NAME}-data"
    labels:
      app: "${NAME}-${TAG_NAME}"
      template: "${NAME}-deploy"
  spec:
    #storageClassName: "${PERSISTENT_VOLUME_CLASS}"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${PERSISTENT_VOLUME_SIZE}"              
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the OpenShift resources associated to the
    server instance.
  required: true
  value: patroni
- name: TAG_NAME
  description: The image tag name to pull for the deployment.
  required: true
- name: IMAGE_REGISTRY_HOST
  description: The image tag name to pull for the deployment.
  required: true    
- name: IMAGE_NAMESPACE
  description: The location for your image streams (Tools Workspace).
  required: true
- name: IMAGE_TAG
  description: The image tag to pull for the deployment.
  required: true 
- name: PERSISTENT_VOLUME_SIZE
  displayName: Persistent Volume Size
  description: The size of the persistent volume , e.g. 512Mi, 1Gi, 2Gi.
  required: true
  value: 1Gi               
     
