name: Boat Tracker App Deployment

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  deploy-to-oc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${{secrets.OPENSHIFT_SERVER}} --token=${{secrets.OPENSHIFT_TOKEN}} --insecure-skip-tls-verify  