name: Boat Tracker App Deployment

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  deploy-to-oc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List files in working directory
        run: ls 

      - name: print working directory
        run: pwd

      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${{secrets.OPENSHIFT_SERVER}} --token=${{secrets.OPENSHIFT_TOKEN}} --insecure-skip-tls-verify
      
      - name: Watch new rollout (trigger by image change in Openshift)
        shell: bash
        run: |
          oc project myproject  
          oc process -f postgresql-dc.yaml --param-file=${{secrets.OPENSHIFT_SERVER_ENV}}.env --ignore-unknown-parameters=true | oc apply -f -    