name: Boat Tracker App Deployment

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  deploy-to-oc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List files in working directory
        run: ls 

      - name: print working directory
        run: pwd

      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${{secrets.OPENSHIFT_SERVER}} --token=${{secrets.OPENSHIFT_TOKEN}} --insecure-skip-tls-verify
      
      - name: Watch new rollout (trigger by image change in Openshift)
        shell: bash
        run: |
          oc project myproject  
          oc process -f deployment/openshift/postgresql-dc.yaml --param-file=deployment/openshift/${{secrets.OPENSHIFT_SERVER_ENV}}.env --ignore-unknown-parameters=true | oc apply -f -
          oc process -f deployment/openshift/webapi-bc.yaml | oc apply -f - 
          oc process -f deployment/openshift/webapi-dc.yaml --param-file=deployment/openshift/${{secrets.OPENSHIFT_SERVER_ENV}}.env --ignore-unknown-parameters=true | oc apply -f -
          oc process -f deployment/openshift/webapp-bc.yaml | oc apply -f -
          oc process -f deployment/openshift/webapp-dc.yaml --param-file=deployment/openshift/${{secrets.OPENSHIFT_SERVER_ENV}}.env --ignore-unknown-parameters=true | oc apply -f -   