name: Forms flow DEV CD

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  deploy-to-oc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2